### ISSUE TITLE
Unable to find xelogstash.exe in download files

### ISSUE THREAD

**Issue by kumar007007** [billgraziano/xelogstash#21]
Downloaded but unable to find xelogstash.exe file

**Comment by billgraziano** [comment]
I just checked and xelogstash.exe is in ZIP in the releases.

**Comment by lay1379** [comment]
Dear bill,

I downloaded the zip file and also not able to get the xelogstash.exe file.

**Comment by billgraziano** [comment]
I just checked the latest download.  I downloaded the ZIP opened it and was able to get the .EXE file.  It is in a subdirectory in the zip file.  What do you see in the ZIP file?
