### ISSUE TITLE
Provide steps for generating xelogstash.exe 

### ISSUE THREAD

**Issue by yeruvass** [billgraziano/xelogstash#47]
@billgraziano 

Could you please provide steps for generating xelogstash.exe file. I have tried to generate exe file in windows but lot of dependence like git,make, go language. I tried same thing in the linux but this related to windows So we could not able to make it to xelogstash.exe . 

Really very helpful if we provide steps to generate the exe file.

**Comment by billgraziano** [comment]
All you should need installed is GO.  I'm on GO 1.14.2.  I added a section at the bottom of the README on building the application.  I'd also suggest building and using SQLXEWRITER instead of xelogstash.
