### ISSUE TITLE
sql: Scan error on column index 1, name "DomainName": converting NULL to string is unsupported

### ISSUE THREAD

**Issue by fgather** [billgraziano/xelogstash#59]
First, thanks for the creation of that library. However, I  might have found an issue: For at least some linux sqlserver versions the following line seems to lead to an error, since the domain cannot be looked up. 

https://github.com/billgraziano/xelogstash/blob/484be6e37b3578750c2ce987e0c27bf17dab4d6b/xe/sqlinfo.go#L79

**Comment by billgraziano** [comment]
Thanks for the feedback.  Sorry it took me so long to get it fixed.  Hopefully this build works better for you.

**Comment by fgather** [comment]
Thanks a lot!
