### ISSUE TITLE
TCP port Exhaustion on the server due to sqlxewriter.exe

### ISSUE THREAD

**Issue by yeruvass** [billgraziano/xelogstash#81]
Hi,
We have installed xelogstash software to collect sql extended events from sql servers and sending events directly to the logstash but we have observed many TCP ports are opening. Attaching all screensho
<img width="523" alt="ELK writer error_reproduced" src="https://user-images.githubusercontent.com/5181193/188400008-e23ce554-2509-4e9c-bedb-3e3f06f1cb2e.PNG">
<img width="671" alt="FCRM_Eventlog" src="https://user-images.githubusercontent.com/5181193/188400020-2a341091-8c25-427a-adbd-198346ce3ae3.PNG">
<img width="605" alt="netTCP_8222022" src="https://user-images.githubusercontent.com/5181193/188400025-93a3615f-864e-4806-8aa0-65c867119e16.PNG">
t here. please help us to provide solution on this. 

Thanks
Sundar

**Comment by billgraziano** [comment]
How many SQL Servers are you polling?  How soon after startup does this happen?

**Comment by billgraziano** [comment]
[heap.go.zip](https://github.com/billgraziano/xelogstash/files/9497903/heap.go.zip)

**Comment by billgraziano** [comment]
[goroutine.zip](https://github.com/billgraziano/xelogstash/files/9497962/goroutine.zip)
