### ISSUE TITLE
xelogstash in Linux 8.8

### ISSUE THREAD

**Issue by tahseenfa** [billgraziano/xelogstash#96]
Hi Team,

I want to fetch trace and extended logs from the **Red Hat Enterprise Linux 8.8.**
I have the files kept in -` /db/extended_event_logs/ ` of trace and extended events with file extension `.xel and .trc`

Kindly help here to know the process of xelogstash for a Linux based environment.

Thanks,
Tahseen

**Comment by billgraziano** [comment]
This queries the Extended Events through SQL Server.  It doesn't read the files directly.  The README has instructions on how to read the events.
